#ifndef TYPHON_FRAMEWORK_EXECUTION_PRIORITIES_HPP
#define TYPHON_FRAMEWORK_EXECUTION_PRIORITIES_HPP

extern int EXEPR_MAIN_GAME_CONTROLLER;
extern int EXEPR_ENVIRON_MGR;
extern int EXEPR_NETWORK_MGR;
extern int EXEPR_CREATURES;

extern void ResolveExecutionPriorities();

#endif // !TYPHON_FRAMEWORK_EXECUTION_PRIORITIES_HPP

