#ifndef UHOBGOBLIN_PRIVATE_SHORT_NAMESPACE_HPP
#define UHOBGOBLIN_PRIVATE_SHORT_NAMESPACE_HPP

#if defined(HOBGOBLIN_SHORT_NAMESPACE) && !defined(UHOBGOBLIN_NAMESPACE_SHORTENED)
#define UHOBGOBLIN_NAMESPACE_SHORTENED

namespace hg = jbatnozic::hobgoblin;

#endif

#endif // !UHOBGOBLIN_PRIVATE_SHORT_NAMESPACE_HPP

