
#undef HOBGOBLIN_NAMESPACE_START
#undef HOBGOBLIN_NAMESPACE_END
#undef CURRENT_FUNCTION
#undef NO_COPY
#undef NO_MOVE
#undef PASSKEY
#undef SELF
#undef SWITCH_FALLTHROUGH
#undef NO_OP
#undef CRTP_METHOD
#undef FRIEND_ACCESS