#pragma once

#define PRIORITY_NETWORKMGR  15
#define PRIORITY_GAMEPLAYMGR 10
#define PRIORITY_ACTOR        5
#define PRIORITY_WINDOWMGR    0

#define STATE_BUFFERING_LENGTH 2

#define WINDOW_WIDTH  800
#define WINDOW_HEIGHT 600
#define DESIRED_FRAMERATE 60
